"""Add bakim_durum and notlar to Parca

Revision ID: 2ad5e3f4c3e2
Revises: 
Create Date: 2025-05-16 15:01:18.168202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad5e3f4c3e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bakim_kaydi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parca_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('teknisyen', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['parca_id'], ['parcalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('parca')
    with op.batch_alter_table('parcalar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bakim_durum', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notlar', sa.Text(), nullable=True))
        batch_op.alter_column('son_bakim_tarihi',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('bakim_dongusu',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcalar', schema=None) as batch_op:
        batch_op.alter_column('bakim_dongusu',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('son_bakim_tarihi',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('notlar')
        batch_op.drop_column('bakim_durum')

    op.create_table('parca',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('barcode', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ekipman_turu', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model_adi', sa.VARCHAR(length=100), nullable=False),
    sa.Column('konum', sa.VARCHAR(length=100), nullable=False),
    sa.Column('durum', sa.VARCHAR(length=100), nullable=False),
    sa.Column('bir_sonraki_bakim', sa.DATE(), nullable=True),
    sa.Column('son_bakim_tarihi', sa.DATE(), nullable=True),
    sa.Column('bakim_dongusu', sa.VARCHAR(length=50), nullable=True),
    sa.Column('kisa_aciklama', sa.TEXT(), nullable=True),
    sa.Column('yuk_kapasitesi', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sorumlu_kisi', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('bakim_kaydi')
    # ### end Alembic commands ###
