"""add bakim_yaklasma_gunu to settings

Revision ID: af9093234717
Revises: 2ad5e3f4c3e2
Create Date: 2025-06-14 16:33:40.216920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9093234717'
down_revision = '2ad5e3f4c3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bakim_yaklasma_gunu', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('bakim_yaklasma_gunu')

    # ### end Alembic commands ###
